name: CI

on:
- push
- pull_request

jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.8'
          tox_env: 'py38-dj22-drf313'
        - python: '3.9'
          tox_env: 'py39-dj22-drf313'
        - python: '3.8'
          tox_env: 'py38-dj32-drf314'
        - python: '3.9'
          tox_env: 'py39-dj32-drf314'
        - python: '3.10'
          tox_env: 'py310-dj32-drf314'
        - python: '3.8'
          tox_env: 'py38-dj42-drf314'
        - python: '3.9'
          tox_env: 'py39-dj42-drf314'
        - python: '3.10'
          tox_env: 'py310-dj42-drf314'
        - python: '3.11'
          tox_env: 'py311-dj42-drf314'
        - python: '3.12'
          tox_env: 'py312-dj42-drf314'
        - python: '3.10'
          tox_env: 'py310-dj50-drf314'
        - python: '3.11'
          tox_env: 'py311-dj50-drf314'
        - python: '3.12'
          tox_env: 'py312-dj50-drf314'

    runs-on: ubuntu-22.04
    name: Python ${{ matrix.python }} with packages ${{ matrix.tox_env }}
    steps:
    - uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: install dependencies
      run: python -m pip install tox coverage

    - name: run test suite
      env:
        TOX_ENV: ${{ matrix.tox_env }}
      run: tox -ve $TOX_ENV

    - name: run coverage
      env:
        TOX_ENV: ${{ matrix.tox_env }}
      run: |
        python -m pip install codecov
        codecov -e TOX_ENV
